package org.eba.migrator;

import com.healthmarketscience.jackcess.Column;
import com.healthmarketscience.jackcess.Database;
import com.healthmarketscience.jackcess.Relationship;
import com.healthmarketscience.jackcess.Table;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Extracts the full DDL schema from an MS Access database:
 * <ul>
 *   <li>{@code /app/out/schema/tables.sql}       – CREATE TABLE statements</li>
 *   <li>{@code /app/out/schema/foreign_keys.sql} – ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY</li>
 *   <li>{@code /app/out/schema/avro/<Table>.avsc} – pretty-printed Avro schema per table</li>
 * </ul>
 *
 * Tables whose names begin with {@code ~} are treated as Access system/temp
 * tables and are silently skipped.
 */
public final class SchemaExtractor {

    private static final Logger log = LoggerFactory.getLogger(SchemaExtractor.class);

    private SchemaExtractor() {}

    // ── Public API ──────────────────────────────────────────────────────────

    /**
     * Iterates all non-system tables, generates DDL SQL files, and returns the
     * dynamically built Avro schema for each table (keyed by original table name).
     */
    public static Map<String, Schema> extractDDL(
            Database db, Set<String> tableNames, Path schemaDir) throws IOException {

        Map<String, Schema> avroSchemas = new LinkedHashMap<>();

        StringBuilder tablesSql = new StringBuilder();
        tablesSql.append("-- EBA Taxonomy – CREATE TABLE statements\n");
        tablesSql.append("-- Generated by EBA Taxonomy Migrator Phase 1\n\n");

        for (String tableName : tableNames) {
            if (tableName.startsWith("~")) {
                log.debug("DDL: skipping system table '{}'", tableName);
                continue;
            }

            try {
                Table table = db.getTable(tableName);
                List<? extends Column> columns = table.getColumns();

                // Build Avro schema first (reused for Parquet later)
                Schema avroSchema = buildAvroSchema(tableName, columns);
                avroSchemas.put(tableName, avroSchema);

                // ── CREATE TABLE ──────────────────────────────────────────
                tablesSql.append("CREATE TABLE ").append(dquote(tableName)).append(" (\n");

                List<String> colDefs = new ArrayList<>();
                for (Column col : columns) {
                    StringBuilder def = new StringBuilder("    ");
                    def.append(dquote(col.getName()));
                    def.append(" ");
                    def.append(TypeMapper.toSqlType(col));
                    colDefs.add(def.toString());
                }
                tablesSql.append(String.join(",\n", colDefs));
                tablesSql.append("\n);\n\n");

            } catch (Exception e) {
                log.error("DDL: failed for table '{}': {}", tableName, e.getMessage(), e);
            }
        }

        // ── Write tables.sql ──────────────────────────────────────────────
        Path tablesSqlPath = schemaDir.resolve("tables.sql");
        Files.writeString(tablesSqlPath, tablesSql);
        log.info("Written: {} ({} tables)", tablesSqlPath, avroSchemas.size());

        // ── Write foreign_keys.sql ────────────────────────────────────────
        writeForeignKeys(db, schemaDir, tableNames);

        return avroSchemas;
    }

    /**
     * Exports a single Avro schema as a pretty-printed {@code .avsc} JSON file.
     */
    public static void exportAvroSchema(String tableName, Schema avroSchema, Path avroDir)
            throws IOException {
        String fileName = tableName.replaceAll("[^a-zA-Z0-9_\\-]", "_") + ".avsc";
        Path avscPath = avroDir.resolve(fileName);
        Files.writeString(avscPath, avroSchema.toString(true));
        log.debug("Written Avro schema: {}", avscPath);
    }

    // ── Schema building ─────────────────────────────────────────────────────

    /**
     * Dynamically constructs an Avro {@code Schema.Type.RECORD} from Jackcess
     * column metadata.  Field names are sanitised to valid Avro identifiers;
     * the original Access name is stored in each field's {@code doc} attribute.
     */
    public static Schema buildAvroSchema(String tableName, List<? extends Column> columns) {
        String safeRecordName = TypeMapper.toAvroName(tableName);

        SchemaBuilder.FieldAssembler<Schema> fields = SchemaBuilder
                .record(safeRecordName)
                .namespace("org.eba.taxonomy")
                .doc("EBA taxonomy table: " + tableName)
                .fields();

        for (Column col : columns) {
            String avroFieldName = TypeMapper.toAvroName(col.getName());
            Schema fieldType    = TypeMapper.toAvroFieldSchema(col.getType());
            fields.name(avroFieldName)
                  .doc(col.getName())   // original Access column name preserved here
                  .type(fieldType)
                  .withDefault(null);
        }
        return fields.endRecord();
    }

    // ── Internals ───────────────────────────────────────────────────────────

    private static void writeForeignKeys(Database db, Path schemaDir, Set<String> tableNames)
            throws IOException {

        StringBuilder fkSql = new StringBuilder();
        fkSql.append("-- EBA Taxonomy – FOREIGN KEY constraints\n");
        fkSql.append("-- Generated by EBA Taxonomy Migrator Phase 1\n\n");

        int fkCount = 0;
        try {
            List<Relationship> relationships = db.getRelationships();
            log.info("Found {} relationship(s) in the database.", relationships.size());

            for (Relationship rel : relationships) {
                String fromTable = rel.getFromTable().getName();
                String toTable   = rel.getToTable().getName();

                // Skip if either side is a system/temp table
                if (fromTable.startsWith("~") || toTable.startsWith("~")) continue;

                List<? extends Column> fromCols = rel.getFromColumns();
                List<? extends Column> toCols   = rel.getToColumns();
                if (fromCols.isEmpty() || toCols.isEmpty()) continue;

                // Sanitise the constraint name
                String relName = rel.getName();
                if (relName == null || relName.isBlank()) {
                    relName = "fk_" + fromTable + "_" + toTable;
                }
                relName = relName.replaceAll("[^A-Za-z0-9_]", "_");

                fkSql.append("ALTER TABLE ").append(dquote(fromTable)).append("\n");
                fkSql.append("    ADD CONSTRAINT ").append(dquote(relName)).append("\n");
                fkSql.append("    FOREIGN KEY (");

                List<String> fromColNames = new ArrayList<>();
                for (Column c : fromCols) fromColNames.add(dquote(c.getName()));
                fkSql.append(String.join(", ", fromColNames));
                fkSql.append(")\n");

                fkSql.append("    REFERENCES ").append(dquote(toTable)).append(" (");
                List<String> toColNames = new ArrayList<>();
                for (Column c : toCols) toColNames.add(dquote(c.getName()));
                fkSql.append(String.join(", ", toColNames));
                fkSql.append(");\n\n");

                fkCount++;
            }
        } catch (Exception e) {
            log.error("Failed to extract foreign keys: {}", e.getMessage(), e);
        }

        Path fkPath = schemaDir.resolve("foreign_keys.sql");
        Files.writeString(fkPath, fkSql);
        log.info("Written: {} ({} FK constraint(s))", fkPath, fkCount);
    }

    /** Wraps an identifier in standard SQL double-quotes, escaping any inner quotes. */
    private static String dquote(String identifier) {
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }
}