-- EBA Taxonomy – FOREIGN KEY constraints
-- Generated by EBA Taxonomy Migrator Phase 1

ALTER TABLE "Category"
    ADD CONSTRAINT "FKItemCatego525178"
    FOREIGN KEY ("CategoryID")
    REFERENCES "ItemCategory" ("CategoryID");

ALTER TABLE "Category"
    ADD CONSTRAINT "FKPropertyCa732103"
    FOREIGN KEY ("CategoryID")
    REFERENCES "PropertyCategory" ("CategoryID");

ALTER TABLE "Category"
    ADD CONSTRAINT "FKSubCategor106944"
    FOREIGN KEY ("CategoryID")
    REFERENCES "SubCategory" ("CategoryID");

ALTER TABLE "Category"
    ADD CONSTRAINT "FKSuperCateg825110"
    FOREIGN KEY ("CategoryID")
    REFERENCES "SuperCategoryComposition" ("SuperCategoryID");

ALTER TABLE "Category"
    ADD CONSTRAINT "FKSuperCateg831013"
    FOREIGN KEY ("CategoryID")
    REFERENCES "SuperCategoryComposition" ("CategoryID");

ALTER TABLE "Cell"
    ADD CONSTRAINT "FKOperandRef881860"
    FOREIGN KEY ("CellID")
    REFERENCES "OperandReferenceLocation" ("CellID");

ALTER TABLE "Cell"
    ADD CONSTRAINT "FKTableVersi883192"
    FOREIGN KEY ("CellID")
    REFERENCES "TableVersionCell" ("CellID");

ALTER TABLE "ChangeLog"
    ADD CONSTRAINT "FK_ChangeLogAttribute_Action"
    FOREIGN KEY ("ActionID")
    REFERENCES "ChangeLogAttribute" ("ActionID");

ALTER TABLE "CompoundKey"
    ADD CONSTRAINT "FKKeyComposi60275"
    FOREIGN KEY ("KeyID")
    REFERENCES "KeyComposition" ("KeyID");

ALTER TABLE "CompoundKey"
    ADD CONSTRAINT "FKModuleVers404440"
    FOREIGN KEY ("KeyID")
    REFERENCES "ModuleVersion" ("GlobalKeyID");

ALTER TABLE "CompoundKey"
    ADD CONSTRAINT "FKTableVersi41391"
    FOREIGN KEY ("KeyID")
    REFERENCES "TableVersion" ("KeyID");

ALTER TABLE "CompoundKey"
    ADD CONSTRAINT "FKVariableVe384231"
    FOREIGN KEY ("KeyID")
    REFERENCES "VariableVersion" ("KeyID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKCategory743377"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Category" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKCell802206"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Cell" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKCompoundKe582932"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "CompoundKey" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKContext288100"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Context" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKDocument532809"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Document" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKDocumentVe733361"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "DocumentVersion" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKFramework245233"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Framework" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKHeader666999"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Header" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKHeaderVers859687"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "HeaderVersion" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKItem609261"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Item" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKModule154031"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Module" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKModuleVers675097"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "ModuleVersion" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKOperation195728"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Operation" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKOperationV331822"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "OperationVersion" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKOrganisati59058"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Organisation" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKProperty396814"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Property" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKReference310449"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Reference" ("ConceptGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKRelatedCon732301"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "RelatedConcept" ("ConceptGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKRelease352135"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Release" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKSubCategor997555"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "SubCategory" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKSubCategor420859"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "SubCategoryItem" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKSubdivisio562876"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Subdivision" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKTable335524"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Table" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKTableAssoc473493"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "TableAssociation" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKTableGroup95711"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "TableGroup" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKTableVersi932385"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "TableVersion" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKTranslatio68568"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Translation" ("ConceptGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKVariable129247"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "Variable" ("RowGUID");

ALTER TABLE "Concept"
    ADD CONSTRAINT "FKVariableVe613582"
    FOREIGN KEY ("ConceptGUID")
    REFERENCES "VariableVersion" ("RowGUID");

ALTER TABLE "ConceptRelation"
    ADD CONSTRAINT "FKRelatedCon174029"
    FOREIGN KEY ("ConceptRelationID")
    REFERENCES "RelatedConcept" ("ConceptRelationID");

ALTER TABLE "Context"
    ADD CONSTRAINT "FKCompoundIt742108"
    FOREIGN KEY ("ContextID")
    REFERENCES "CompoundItemContext" ("ContextID");

ALTER TABLE "Context"
    ADD CONSTRAINT "FKContextCom82273"
    FOREIGN KEY ("ContextID")
    REFERENCES "ContextComposition" ("ContextID");

ALTER TABLE "Context"
    ADD CONSTRAINT "FKHeaderVers399933"
    FOREIGN KEY ("ContextID")
    REFERENCES "HeaderVersion" ("ContextID");

ALTER TABLE "Context"
    ADD CONSTRAINT "FKTableVersi607859"
    FOREIGN KEY ("ContextID")
    REFERENCES "TableVersion" ("ContextID");

ALTER TABLE "Context"
    ADD CONSTRAINT "FKVariableVe817762"
    FOREIGN KEY ("ContextID")
    REFERENCES "VariableVersion" ("ContextID");

ALTER TABLE "DataType"
    ADD CONSTRAINT "FKProperty442698"
    FOREIGN KEY ("DataTypeID")
    REFERENCES "Property" ("DataTypeID");

ALTER TABLE "Document"
    ADD CONSTRAINT "FKDocumentVe77896"
    FOREIGN KEY ("DocumentID")
    REFERENCES "DocumentVersion" ("DocumentID");

ALTER TABLE "DocumentVersion"
    ADD CONSTRAINT "FKSubdivisio226639"
    FOREIGN KEY ("DocumentVID")
    REFERENCES "Subdivision" ("DocumentVID");

ALTER TABLE "DPMAttribute"
    ADD CONSTRAINT "FK_ChangeLogAttribute_Attribute"
    FOREIGN KEY ("AttributeID")
    REFERENCES "ChangeLogAttribute" ("AttributeID");

ALTER TABLE "DPMAttribute"
    ADD CONSTRAINT "FKTranslatio100921"
    FOREIGN KEY ("AttributeID")
    REFERENCES "Translation" ("AttributeID");

ALTER TABLE "DPMClass"
    ADD CONSTRAINT "FK_ChangeLog_DPMClass"
    FOREIGN KEY ("ClassID")
    REFERENCES "ChangeLog" ("ClassID");

ALTER TABLE "DPMClass"
    ADD CONSTRAINT "FKConcept762157"
    FOREIGN KEY ("ClassID")
    REFERENCES "Concept" ("ClassID");

ALTER TABLE "DPMClass"
    ADD CONSTRAINT "FKDPMAttribu969215"
    FOREIGN KEY ("ClassID")
    REFERENCES "DPMAttribute" ("ClassID");

ALTER TABLE "Framework"
    ADD CONSTRAINT "FKModule328191"
    FOREIGN KEY ("FrameworkID")
    REFERENCES "Module" ("FrameworkID");

ALTER TABLE "Framework"
    ADD CONSTRAINT "FK__Operation__Frame__22401542"
    FOREIGN KEY ("FrameworkID")
    REFERENCES "OperationCodePrefix" ("FrameworkID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKCell269422"
    FOREIGN KEY ("HeaderID")
    REFERENCES "Cell" ("ColumnID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKCell197808"
    FOREIGN KEY ("HeaderID")
    REFERENCES "Cell" ("RowID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKCell269161"
    FOREIGN KEY ("HeaderID")
    REFERENCES "Cell" ("SheetID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKHeaderVers371312"
    FOREIGN KEY ("HeaderID")
    REFERENCES "HeaderVersion" ("HeaderID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKKeyHeaderM636398"
    FOREIGN KEY ("HeaderID")
    REFERENCES "KeyHeaderMapping" ("ForeignKeyHeaderID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKKeyHeaderM108065"
    FOREIGN KEY ("HeaderID")
    REFERENCES "KeyHeaderMapping" ("PrimaryKeyHeaderID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKTableAssoc840717"
    FOREIGN KEY ("HeaderID")
    REFERENCES "TableAssociation" ("SubtypeDiscriminator");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKTableVersi692213"
    FOREIGN KEY ("HeaderID")
    REFERENCES "TableVersionHeader" ("HeaderID");

ALTER TABLE "Header"
    ADD CONSTRAINT "FKTableVersi102009"
    FOREIGN KEY ("HeaderID")
    REFERENCES "TableVersionHeader" ("ParentHeaderID");

ALTER TABLE "HeaderVersion"
    ADD CONSTRAINT "FKTableVersi622961"
    FOREIGN KEY ("HeaderVID")
    REFERENCES "TableVersionHeader" ("HeaderVID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKCompoundIt363990"
    FOREIGN KEY ("ItemID")
    REFERENCES "CompoundItemContext" ("ItemID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKContextCom783218"
    FOREIGN KEY ("ItemID")
    REFERENCES "ContextComposition" ("ItemID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKItemCatego931286"
    FOREIGN KEY ("ItemID")
    REFERENCES "ItemCategory" ("ItemID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKOperandRef468801"
    FOREIGN KEY ("ItemID")
    REFERENCES "OperandReference" ("ItemID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKProperty578267"
    FOREIGN KEY ("ItemID")
    REFERENCES "Property" ("PropertyID");

ALTER TABLE "Item"
    ADD CONSTRAINT "FKSubCategor855005"
    FOREIGN KEY ("ItemID")
    REFERENCES "SubCategoryItem" ("ItemID");

ALTER TABLE "Language"
    ADD CONSTRAINT "FKTranslatio815983"
    FOREIGN KEY ("LanguageCode")
    REFERENCES "Translation" ("LanguageCode");

ALTER TABLE "Module"
    ADD CONSTRAINT "FKModuleVers49266"
    FOREIGN KEY ("ModuleID")
    REFERENCES "ModuleVersion" ("ModuleID");

ALTER TABLE "Module"
    ADD CONSTRAINT "FKVariableCa665513"
    FOREIGN KEY ("ModuleID")
    REFERENCES "VariableCalculation" ("ModuleID");

ALTER TABLE "ModuleVersion"
    ADD CONSTRAINT "FKModulePara783919"
    FOREIGN KEY ("ModuleVID")
    REFERENCES "ModuleParameters" ("ModuleVID");

ALTER TABLE "ModuleVersion"
    ADD CONSTRAINT "FKModuleVers724892"
    FOREIGN KEY ("ModuleVID")
    REFERENCES "ModuleVersionComposition" ("ModuleVID");

ALTER TABLE "ModuleVersion"
    ADD CONSTRAINT "FKOperationS606932"
    FOREIGN KEY ("ModuleVID")
    REFERENCES "OperationScopeComposition" ("ModuleVID");

ALTER TABLE "OperandReference"
    ADD CONSTRAINT "FKOperandRef286522"
    FOREIGN KEY ("OperandReferenceID")
    REFERENCES "OperandReferenceLocation" ("OperandReferenceID");

ALTER TABLE "Operation"
    ADD CONSTRAINT "FKOperationV552560"
    FOREIGN KEY ("OperationID")
    REFERENCES "OperationVersion" ("OperationID");

ALTER TABLE "OperationNode"
    ADD CONSTRAINT "FKOperandRef996703"
    FOREIGN KEY ("NodeID")
    REFERENCES "OperandReference" ("NodeID");

ALTER TABLE "OperationScope"
    ADD CONSTRAINT "FKOperationS658414"
    FOREIGN KEY ("OperationScopeID")
    REFERENCES "OperationScopeComposition" ("OperationScopeID");

ALTER TABLE "OperationVersion"
    ADD CONSTRAINT "FKOperationN727504"
    FOREIGN KEY ("OperationVID")
    REFERENCES "OperationNode" ("OperationVID");

ALTER TABLE "OperationVersion"
    ADD CONSTRAINT "FKOperationS602068"
    FOREIGN KEY ("OperationVID")
    REFERENCES "OperationScope" ("OperationVID");

ALTER TABLE "OperationVersion"
    ADD CONSTRAINT "FK_OperationVersion"
    FOREIGN KEY ("OperationVID")
    REFERENCES "OperationVersionData" ("OperationVID");

ALTER TABLE "OperationVersion"
    ADD CONSTRAINT "FKVariableCa536997"
    FOREIGN KEY ("OperationVID")
    REFERENCES "VariableCalculation" ("OperationVID");

ALTER TABLE "Operator"
    ADD CONSTRAINT "FKOperationN554566"
    FOREIGN KEY ("OperatorID")
    REFERENCES "OperationNode" ("OperatorID");

ALTER TABLE "Operator"
    ADD CONSTRAINT "FKOperatorAr930098"
    FOREIGN KEY ("OperatorID")
    REFERENCES "OperatorArgument" ("OperatorID");

ALTER TABLE "Operator"
    ADD CONSTRAINT "FKSubCategor651879"
    FOREIGN KEY ("OperatorID")
    REFERENCES "SubCategoryItem" ("ComparisonOperatorID");

ALTER TABLE "Operator"
    ADD CONSTRAINT "FKSubCategor541932"
    FOREIGN KEY ("OperatorID")
    REFERENCES "SubCategoryItem" ("ArithmeticOperatorID");

ALTER TABLE "OperatorArgument"
    ADD CONSTRAINT "FKOperationN128256"
    FOREIGN KEY ("ArgumentID")
    REFERENCES "OperationNode" ("ArgumentID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Category_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Category" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Cell_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Cell" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_CompoundKey_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "CompoundKey" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FKConcept928356"
    FOREIGN KEY ("OrgID")
    REFERENCES "Concept" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Context_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Context" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FKDocument854565"
    FOREIGN KEY ("OrgID")
    REFERENCES "Document" ("OrgID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Framework_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Framework" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Header_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Header" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Item_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Item" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Module_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Module" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Operation_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Operation" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Property_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Property" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Release_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Release" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_SubCategory_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "SubCategory" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Subdivision_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Subdivision" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Table_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Table" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_TableAssociation_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "TableAssociation" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_TableGroup_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "TableGroup" ("OwnerID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FKTranslatio481615"
    FOREIGN KEY ("OrgID")
    REFERENCES "Translation" ("TranslatorID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FKUser397109"
    FOREIGN KEY ("OrgID")
    REFERENCES "User" ("OrgID");

ALTER TABLE "Organisation"
    ADD CONSTRAINT "FK_Variable_Owner"
    FOREIGN KEY ("OrgID")
    REFERENCES "Variable" ("OwnerID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKContextCom93794"
    FOREIGN KEY ("PropertyID")
    REFERENCES "ContextComposition" ("PropertyID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKHeaderVers395590"
    FOREIGN KEY ("PropertyID")
    REFERENCES "HeaderVersion" ("PropertyID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKOperandRef220623"
    FOREIGN KEY ("PropertyID")
    REFERENCES "OperandReference" ("PropertyID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKPropertyCa906402"
    FOREIGN KEY ("PropertyID")
    REFERENCES "PropertyCategory" ("PropertyID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKTableVersi783926"
    FOREIGN KEY ("PropertyID")
    REFERENCES "TableVersion" ("PropertyID");

ALTER TABLE "Property"
    ADD CONSTRAINT "FKVariableVe641695"
    FOREIGN KEY ("PropertyID")
    REFERENCES "VariableVersion" ("PropertyID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKCategory_Release"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "Category" ("CreatedRelease");

ALTER TABLE "Release"
    ADD CONSTRAINT "FK_ChangeLog_Release"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "ChangeLog" ("ReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKCompoundIt265848"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "CompoundItemContext" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKCompoundIt823291"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "CompoundItemContext" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKHeaderVers165467"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "HeaderVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKHeaderVers608023"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "HeaderVersion" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKItemCatego390588"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "ItemCategory" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKItemCatego833144"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "ItemCategory" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKModuleVers649942"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "ModuleVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKModuleVers207386"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "ModuleVersion" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FK_OperationScope_CreatedRelease"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "OperationScope" ("CreatedReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKOperationV693332"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "OperationVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKOperationV135889"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "OperationVersion" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKPropertyCa323720"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "PropertyCategory" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKPropertyCa118836"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "PropertyCategory" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKSubCategor801303"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "SubCategoryVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKSubCategor727730"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "SubCategoryVersion" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKSuperCateg746780"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "SuperCategoryComposition" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKSuperCateg782253"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "SuperCategoryComposition" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableGroup70556"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableGroup" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableGroup372000"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableGroup" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableGroup776142"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableGroupComposition" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableGroup752891"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableGroupComposition" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableVersi957540"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKTableVersi571493"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "TableVersion" ("EndReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "VariableGeneration_FK"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "VariableGeneration" ("ReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKVariableVe588427"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "VariableVersion" ("StartReleaseID");

ALTER TABLE "Release"
    ADD CONSTRAINT "FKVariableVe854128"
    FOREIGN KEY ("ReleaseID")
    REFERENCES "VariableVersion" ("EndReleaseID");

ALTER TABLE "Role"
    ADD CONSTRAINT "FKUserRole532117"
    FOREIGN KEY ("RoleID")
    REFERENCES "UserRole" ("RoleID");

ALTER TABLE "SubCategory"
    ADD CONSTRAINT "FKOperandRef7492"
    FOREIGN KEY ("SubCategoryID")
    REFERENCES "OperandReference" ("SubCategoryID");

ALTER TABLE "SubCategory"
    ADD CONSTRAINT "FKSubCategor168279"
    FOREIGN KEY ("SubCategoryID")
    REFERENCES "SubCategoryVersion" ("SubCategoryID");

ALTER TABLE "SubCategoryVersion"
    ADD CONSTRAINT "FKHeaderVers717070"
    FOREIGN KEY ("SubCategoryVID")
    REFERENCES "HeaderVersion" ("SubCategoryVID");

ALTER TABLE "SubCategoryVersion"
    ADD CONSTRAINT "FKSubCategor693348"
    FOREIGN KEY ("SubCategoryVID")
    REFERENCES "SubCategoryItem" ("SubCategoryVID");

ALTER TABLE "SubCategoryVersion"
    ADD CONSTRAINT "FKVariableVe470965"
    FOREIGN KEY ("SubCategoryVID")
    REFERENCES "VariableVersion" ("SubCategoryVID");

ALTER TABLE "Subdivision"
    ADD CONSTRAINT "FKReference764763"
    FOREIGN KEY ("SubdivisionID")
    REFERENCES "Reference" ("SubdivisionID");

ALTER TABLE "SubdivisionType"
    ADD CONSTRAINT "FKSubdivisio763080"
    FOREIGN KEY ("SubdivisionTypeID")
    REFERENCES "Subdivision" ("SubdivisionTypeID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKCell154740"
    FOREIGN KEY ("TableID")
    REFERENCES "Cell" ("TableID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKHeader347644"
    FOREIGN KEY ("TableID")
    REFERENCES "Header" ("TableID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKModuleVers801841"
    FOREIGN KEY ("TableID")
    REFERENCES "ModuleVersionComposition" ("TableID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKTableGroup263656"
    FOREIGN KEY ("TableID")
    REFERENCES "TableGroupComposition" ("TableID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKTableVersi82258"
    FOREIGN KEY ("TableID")
    REFERENCES "TableVersion" ("TableID");

ALTER TABLE "Table"
    ADD CONSTRAINT "FKTableVersi275581"
    FOREIGN KEY ("TableID")
    REFERENCES "TableVersion" ("AbstractTableID");

ALTER TABLE "TableAssociation"
    ADD CONSTRAINT "FKKeyHeaderM189933"
    FOREIGN KEY ("AssociationID")
    REFERENCES "KeyHeaderMapping" ("AssociationID");

ALTER TABLE "TableGroup"
    ADD CONSTRAINT "FKTableGroup783556"
    FOREIGN KEY ("TableGroupID")
    REFERENCES "TableGroupComposition" ("TableGroupID");

ALTER TABLE "TableVersion"
    ADD CONSTRAINT "FKModuleVers2767"
    FOREIGN KEY ("TableVID")
    REFERENCES "ModuleVersionComposition" ("TableVID");

ALTER TABLE "TableVersion"
    ADD CONSTRAINT "FKTableAssoc424624"
    FOREIGN KEY ("TableVID")
    REFERENCES "TableAssociation" ("ChildTableVID");

ALTER TABLE "TableVersion"
    ADD CONSTRAINT "FKTableAssoc546002"
    FOREIGN KEY ("TableVID")
    REFERENCES "TableAssociation" ("ParentTableVID");

ALTER TABLE "TableVersion"
    ADD CONSTRAINT "FKTableVersi257568"
    FOREIGN KEY ("TableVID")
    REFERENCES "TableVersionCell" ("TableVID");

ALTER TABLE "TableVersion"
    ADD CONSTRAINT "FKTableVersi765341"
    FOREIGN KEY ("TableVID")
    REFERENCES "TableVersionHeader" ("TableVID");

ALTER TABLE "User"
    ADD CONSTRAINT "FKUserRole396295"
    FOREIGN KEY ("UserID")
    REFERENCES "UserRole" ("UserID");

ALTER TABLE "Variable"
    ADD CONSTRAINT "FKOperandRef200461"
    FOREIGN KEY ("VariableID")
    REFERENCES "OperandReference" ("VariableID");

ALTER TABLE "Variable"
    ADD CONSTRAINT "FKVariableCa154761"
    FOREIGN KEY ("VariableID")
    REFERENCES "VariableCalculation" ("VariableID");

ALTER TABLE "Variable"
    ADD CONSTRAINT "FKVariableVe350057"
    FOREIGN KEY ("VariableID")
    REFERENCES "VariableVersion" ("VariableID");

ALTER TABLE "VariableVersion"
    ADD CONSTRAINT "FKHeaderVers699034"
    FOREIGN KEY ("VariableVID")
    REFERENCES "HeaderVersion" ("KeyVariableVID");

ALTER TABLE "VariableVersion"
    ADD CONSTRAINT "FKKeyComposi605606"
    FOREIGN KEY ("VariableVID")
    REFERENCES "KeyComposition" ("VariableVID");

ALTER TABLE "VariableVersion"
    ADD CONSTRAINT "FKModulePara120772"
    FOREIGN KEY ("VariableVID")
    REFERENCES "ModuleParameters" ("VariableVID");

ALTER TABLE "VariableVersion"
    ADD CONSTRAINT "FKTableVersi872294"
    FOREIGN KEY ("VariableVID")
    REFERENCES "TableVersionCell" ("VariableVID");

